source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '8.0'

link_with 'BoldMovile', 'BoldMovileTests'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'JTAlertView'
pod 'MBSimpleLoadingIndicator'
pod 'Reachability'